testing: true

# Site settings
# Course Info
title: "Ideas in Mathematics"
tagline: "UPenn MATH 1700, Fall 2023."
description: "Ideas in Mathematics"
instructor: "Danny Krashen"
instructor-email: "&#100;&#107;&#114;&#97;&#115;&#104;&#101;&#110;&#64;&#117;&#112;&#101;&#110;&#110;&#46;&#101;&#100;&#117;"
office: "DRL 3E6"
office-hour: "Thursdays 12:00 – 1:00pm"

baseurl: "/ideas_in_math"

# url: "localhost:4000"
url: "http://dkrashen.org"

analytics: "true"

# Build settings
markdown: kramdown
permalink: pretty
